name: Build and Release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v4

    - name: Start maven repository
      run: |
        docker run -itd -p 7765:8080 \
          -e REPOSILITE_OPTS="--token admin:secret" \
          ghcr.io/dzikoysk/reposilite:3.5.17

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: 'maven'
        cache-dependency-path: 'deps.edn'

    - uses: extractions/setup-just@v2
    - uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: latest

    - name: Test
      run: just test

  build-and-release:
    runs-on: ubuntu-latest
    needs:
    - test

    env:
      VERSION: ${{ github.ref_name }}

    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}

    steps:
    - name: Checkout git repo
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: 'maven'
        cache-dependency-path: '**/deps.edn'

    - uses: extractions/setup-just@v2
    - uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: latest

    - name: Build
      run: just build

    - name: Release
      env:
        CLOJARS_USERNAME: infrastructure-kepler16-com
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: just release
